### ISSUE TITLE
Regression in 1.1.3 breaks authentication only for API

### ISSUE THREAD

**Issue by Gibstick** [hkpeprah/marmoset#21]
Latest version can never authenticate. 1.1.2 works, 1.1.3 always gives me:
```
Traceback (most recent call last):
  File "...\autosubmit.py", line 239, in <module>
    submit_all(get_all_params(files), m_username, m_password)
  File "...\autosubmit.py", line 232, in submit_all
    problem.submit(username, password)
  File "...\autosubmit.py", line 102, in submit
    result = marmoset.submit(self.course, self.assignment, self.files)
  File "C:\Python27\lib\site-packages\marmoset\core\marmosetbrowser.py", line 177, in submit
    raise BrowserException("Invalid username/password combination for %s" % self.username)
marmoset.core.marmosetbrowser.BrowserException: Invalid username/password combination for ...
```
However, using it as a script still works. I will investigate further.

Edit: Works if I call the login() method manually, so maybe the constructor is being iffy.

**Comment by Gibstick** [comment]
I found a way to fix it but I have no idea why it works. Sorry for the spam, I misclicked.

**Comment by hkpeprah** [comment]
Good catch, I introduced a bug, didn't notice, I see it now.
